export interface DistrictMapMetadata {
  source: string;
  tileSize: number;
  origin: {x: number; y: number};
  size: {width: number; height: number};
}

export interface LanePoint {
  x: number;
  y: number;
}

export interface LaneDocument {
  corridors: Array<{points: LanePoint[]}>;
  junctions: LanePoint[];
  roadblocks?: Array<LanePoint & {
    vehiclePoses: LanePoint[];
    stinger: LanePoint & {officerPose: LanePoint};
  }>;
}

export function expansionDelta(
  current: DistrictMapMetadata,
  next: DistrictMapMetadata
): Readonly<LanePoint> {
  if (current.source !== next.source) {
    throw new Error(
      `Cannot rebase authored content from ${current.source} onto ${next.source}.`
    );
  }
  if (current.tileSize !== next.tileSize) {
    throw new Error(`Tile size changed from ${current.tileSize} to ${next.tileSize}.`);
  }
  return Object.freeze({
    x: (current.origin.x - next.origin.x) * next.tileSize,
    y: (current.origin.y - next.origin.y) * next.tileSize
  });
}

export function rebaseLaneDocument(
  document: LaneDocument,
  deltaX: number,
  deltaY: number
): LaneDocument {
  return {
    ...document,
    corridors: document.corridors.map((corridor) => ({
      ...corridor,
      points: corridor.points.map((point) => shifted(point, deltaX, deltaY))
    })),
    junctions: document.junctions.map((junction) => shifted(junction, deltaX, deltaY)),
    roadblocks: document.roadblocks?.map((roadblock) => ({
      ...shifted(roadblock, deltaX, deltaY),
      vehiclePoses: roadblock.vehiclePoses.map((pose) => shifted(pose, deltaX, deltaY)),
      stinger: {
        ...shifted(roadblock.stinger, deltaX, deltaY),
        officerPose: shifted(roadblock.stinger.officerPose, deltaX, deltaY)
      }
    }))
  };
}

export function generatedFrameSource(metadata: DistrictMapMetadata): string {
  return `// Generated by scripts/expand-district-map.ts. Do not edit by hand.\n` +
    `export const DISTRICT_MAP_GENERATED_FRAME = Object.freeze({\n` +
    `  origin: Object.freeze({x: ${metadata.origin.x}, y: ${metadata.origin.y}}),\n` +
    `  size: Object.freeze({width: ${metadata.size.width}, height: ${metadata.size.height}}),\n` +
    `  tileSize: ${metadata.tileSize}\n` +
    `});\n`;
}

function shifted<T extends LanePoint>(point: T, deltaX: number, deltaY: number): T {
  return {...point, x: point.x + deltaX, y: point.y + deltaY};
}
