// Generated by scripts/expand-district-map.ts. Do not edit by hand.
export const DISTRICT_MAP_GENERATED_FRAME = Object.freeze({
  origin: Object.freeze({x: 0, y: 0}),
  size: Object.freeze({width: 256, height: 256}),
  tileSize: 64
});
