// Generated by scripts/expand-district-map.ts. Do not edit by hand.
export const DISTRICT_MAP_GENERATED_FRAME = Object.freeze({
  origin: Object.freeze({x: 80, y: 81}),
  size: Object.freeze({width: 96, height: 96}),
  tileSize: 64
});
